In [32]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
#import torch
#import torch.nn as nn
#import torch.optim as optim
from sklearn.preprocessing import LabelEncoder
#from torch.utils.data import TensorDataset, DataLoader
import seaborn as sns
from sklearn.model_selection import GridSearchCV, RandomizedSearchCV
from sklearn.preprocessing import StandardScaler, OrdinalEncoder, LabelEncoder, PolynomialFeatures
from sklearn.impute import SimpleImputer
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer

import tensorflow as tf
import pathlib

In [30]:
data_dir = pathlib.Path("images")
image_paths = list(data_dir.glob("*.jpg"))


In [35]:
# Функція для зчитування та попередньої обробки зображень
def load_and_preprocess_grayscale_image(image_path):
    # Зчитування зображення з файлу
    image = tf.io.read_file(image_path)
    # Декодування зображення в чорно-білий тензор
    image = tf.image.decode_jpeg(image, channels=1)  # Один канал для чорно-білого зображення
    # Зміна розміру зображення (наприклад, 224x224)
    image = tf.image.resize(image, [224, 224])
    # Нормалізація значень пікселів до діапазону [0, 1]
    image /= 255.0
    return image

# Створення потоку даних (Dataset) з усіх шляхів до зображень
dataset = tf.data.Dataset.from_tensor_slices([str(p) for p in image_paths])
# Застосування попередньої обробки до кожного зображення
dataset = dataset.map(load_and_preprocess_grayscale_image)



Тензор:
[[[0.]
  [0.]
  [0.]
  ...
  [0.]
  [0.]
  [0.]]

 [[0.]
  [0.]
  [0.]
  ...
  [0.]
  [0.]
  [0.]]

 [[0.]
  [0.]
  [0.]
  ...
  [0.]
  [0.]
  [0.]]

 ...

 [[0.]
  [0.]
  [0.]
  ...
  [0.]
  [0.]
  [0.]]

 [[0.]
  [0.]
  [0.]
  ...
  [0.]
  [0.]
  [0.]]

 [[0.]
  [0.]
  [0.]
  ...
  [0.]
  [0.]
  [0.]]]
Розмір тензора: (224, 224, 1)
Тензор:
[[[0.]
  [0.]
  [0.]
  ...
  [0.]
  [0.]
  [0.]]

 [[0.]
  [0.]
  [0.]
  ...
  [0.]
  [0.]
  [0.]]

 [[0.]
  [0.]
  [0.]
  ...
  [0.]
  [0.]
  [0.]]

 ...

 [[0.]
  [0.]
  [0.]
  ...
  [0.]
  [0.]
  [0.]]

 [[0.]
  [0.]
  [0.]
  ...
  [0.]
  [0.]
  [0.]]

 [[0.]
  [0.]
  [0.]
  ...
  [0.]
  [0.]
  [0.]]]
Розмір тензора: (224, 224, 1)
Тензор:
[[[0.]
  [0.]
  [0.]
  ...
  [0.]
  [0.]
  [0.]]

 [[0.]
  [0.]
  [0.]
  ...
  [0.]
  [0.]
  [0.]]

 [[0.]
  [0.]
  [0.]
  ...
  [0.]
  [0.]
  [0.]]

 ...

 [[0.]
  [0.]
  [0.]
  ...
  [0.]
  [0.]
  [0.]]

 [[0.]
  [0.]
  [0.]
  ...
  [0.]
  [0.]
  [0.]]

 [[0.]
  [0.]
  [0.]
  ...
  [0.]
  [0.]
  [0.]]

In [ ]:
# Import Data
train_data = pd.read_csv('train.csv')
test_data = pd.read_csv('test.csv')

In [ ]:
train_data

In [ ]:
train=train_data.drop(['id'],axis=1)
test=test_data.drop(['id'],axis=1)

In [22]:
label_encoder = LabelEncoder()

train['species'] = label_encoder.fit_transform(train['species'])
train

species   margin1   margin2   margin3   margin4   margin5   margin6   
0          3  0.007812  0.023438  0.023438  0.003906  0.011719  0.009766  \
1         49  0.005859  0.000000  0.031250  0.015625  0.025391  0.001953   
2         65  0.005859  0.009766  0.019531  0.007812  0.003906  0.005859   
3         94  0.000000  0.003906  0.023438  0.005859  0.021484  0.019531   
4         84  0.005859  0.003906  0.048828  0.009766  0.013672  0.015625   
..       ...       ...       ...       ...       ...       ...       ...   
985       40  0.060547  0.119140  0.007812  0.003906  0.000000  0.148440   
986        5  0.001953  0.003906  0.021484  0.107420  0.001953  0.000000   
987       11  0.001953  0.003906  0.000000  0.021484  0.078125  0.003906   
988       78  0.000000  0.000000  0.046875  0.056641  0.009766  0.000000   
989       50  0.023438  0.019531  0.031250  0.015625  0.005859  0.019531   

      margin7  margin8   margin9  ...  texture55  texture56  texture57   
0    0.027344      0.0  0.001953  ...   0.007812   0.000000   0.002930  \
1    0.019531      0.0  0.000000  ...   0.000977   0.000000   0.000000   
2    0.068359      0.0  0.000000  ...   0.154300   0.000000   0.005859   
3    0.023438      0.0  0.013672  ...   0.000000   0.000977   0.000000   
4    0.005859      0.0  0.000000  ...   0.096680   0.000000   0.021484   
..        ...      ...       ...  ...        ...        ...        ...   
985  0.017578      0.0  0.001953  ...   0.242190   0.000000   0.034180   
986  0.000000      0.0  0.029297  ...   0.170900   0.000000   0.018555   
987  0.007812      0.0  0.003906  ...   0.004883   0.000977   0.004883   
988  0.000000      0.0  0.037109  ...   0.083008   0.030273   0.000977   
989  0.035156      0.0  0.003906  ...   0.000000   0.000000   0.002930   

     texture58  texture59  texture60  texture61  texture62  texture63   
0     0.002930   0.035156   0.000000   0.000000   0.004883   0.000000  \
1     0.000977   0.023438   0.000000   0.000000   0.000977   0.039062   
2     0.000977   0.007812   0.000000   0.000000   0.000000   0.020508   
3     0.000000   0.020508   0.000000   0.000000   0.017578   0.000000   
4     0.000000   0.000000   0.000000   0.000000   0.000000   0.000000   
..         ...        ...        ...        ...        ...        ...   
985   0.000000   0.010742   0.000000   0.000000   0.000000   0.000000   
986   0.000000   0.011719   0.000000   0.000000   0.000977   0.000000   
987   0.027344   0.016602   0.007812   0.000000   0.027344   0.000000   
988   0.002930   0.014648   0.000000   0.041992   0.000000   0.001953   
989   0.000000   0.012695   0.000000   0.000000   0.023438   0.025391   

     texture64  
0     0.025391  
1     0.022461  
2     0.002930  
3     0.047852  
4     0.031250  
..         ...  
985   0.018555  
986   0.021484  
987   0.001953  
988   0.002930  
989   0.022461  

[990 rows x 193 columns]

In [23]:
train.describe()

species     margin1     margin2     margin3     margin4     margin5   
count  990.000000  990.000000  990.000000  990.000000  990.000000  990.000000  \
mean    49.000000    0.017412    0.028539    0.031988    0.023280    0.014264   
std     28.591824    0.019739    0.038855    0.025847    0.028411    0.018390   
min      0.000000    0.000000    0.000000    0.000000    0.000000    0.000000   
25%     24.000000    0.001953    0.001953    0.013672    0.005859    0.001953   
50%     49.000000    0.009766    0.011719    0.025391    0.013672    0.007812   
75%     74.000000    0.025391    0.041016    0.044922    0.029297    0.017578   
max     98.000000    0.087891    0.205080    0.156250    0.169920    0.111330   

          margin6     margin7     margin8     margin9  ...   texture55   
count  990.000000  990.000000  990.000000  990.000000  ...  990.000000  \
mean     0.038579    0.019202    0.001083    0.007167  ...    0.036501   
std      0.052030    0.017511    0.002743    0.008933  ...    0.063403   
min      0.000000    0.000000    0.000000    0.000000  ...    0.000000   
25%      0.000000    0.005859    0.000000    0.001953  ...    0.000000   
50%      0.015625    0.015625    0.000000    0.005859  ...    0.004883   
75%      0.056153    0.029297    0.000000    0.007812  ...    0.043701   
max      0.310550    0.091797    0.031250    0.076172  ...    0.429690   

        texture56   texture57   texture58   texture59   texture60   texture61   
count  990.000000  990.000000  990.000000  990.000000  990.000000  990.000000  \
mean     0.005024    0.015944    0.011586    0.016108    0.014017    0.002688   
std      0.019321    0.023214    0.025040    0.015335    0.060151    0.011415   
min      0.000000    0.000000    0.000000    0.000000    0.000000    0.000000   
25%      0.000000    0.000977    0.000000    0.004883    0.000000    0.000000   
50%      0.000000    0.005859    0.000977    0.012695    0.000000    0.000000   
75%      0.000000    0.022217    0.009766    0.021484    0.000000    0.000000   
max      0.202150    0.172850    0.200200    0.106450    0.578130    0.151370   

        texture62   texture63   texture64  
count  990.000000  990.000000  990.000000  
mean     0.020291    0.008989    0.019420  
std      0.039040    0.013791    0.022768  
min      0.000000    0.000000    0.000000  
25%      0.000000    0.000000    0.000977  
50%      0.003906    0.002930    0.011719  
75%      0.023438    0.012695    0.029297  
max      0.375980    0.086914    0.141600  

[8 rows x 193 columns]

In [24]:
print(train.isnull().sum())

species      0
margin1      0
margin2      0
margin3      0
margin4      0
            ..
texture60    0
texture61    0
texture62    0
texture63    0
texture64    0
Length: 193, dtype: int64


In [25]:
corr_matr = train.corr()
corr_matr["species"].sort_values(ascending = False)

species      1.000000
texture42    0.241976
texture13    0.226016
texture49    0.204843
margin59     0.202767
               ...   
texture55   -0.238099
texture12   -0.251589
margin49    -0.253988
texture5    -0.271063
margin32    -0.284541
Name: species, Length: 193, dtype: float64

In [ ]:
numerical_pipeline = Pipeline([
    ('scaler', StandardScaler())
])
